org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890
org.gradle.java.home=C:\\Program Files (x86)\\Android\\openjdk\\jdk-17.0.14
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890

signing.storePassword=loveya123
signing.keyAlias=loveya_key
signing.keyPassword=loveya123
