sdk.dir=C:\\Program Files (x86)\\Android\\android-sdk
ndk.dir=C:\\Program Files (x86)\\Android\\AndroidNDK\\android-ndk-r23c

# 开发者中心 Gitee 令牌
# 用于把用户账号找回数据上传到 love-ya-data 仓库的 users.json
DEV_GITEE_TOKEN=37638896572f3a95f128b9d7180702fa
